#Goal
string session_id
bool save_map
string map_name
float32 duration_sec

---
# Result
bool success
string map_path
string message

---
# Feedback
geometry_msgs/msg/Pose2D pose
float32 progress
float32 quality
string status